version: "3.11"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_BACKEND_URL=http://20.120.127.80:8000/
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DATASET_PATH=/app/Datasets/IoT.pdf
